export const EMR_TEMPLATES = [
  {
    id: "outpatient",
    name: "Outpatient record template",
    type: "门诊病历",
    fields: [
      "主诉",
      "现病史",
      "既往史",
      "过敏史",
      "体格检查",
      "辅助检查",
      "诊疗计划",
    ],
  },
  {
    id: "inpatient",
    name: "Inpatient record template",
    type: "住院病历",
    fields: [
      "主诉",
      "现病史",
      "既往史",
      "过敏史",
      "入院查体",
      "专科检查",
      "入院诊断依据",
      "诊疗计划",
    ],
  },
  {
    id: "checkup",
    name: "Physical examination report template",
    type: "体检报告",
    fields: [
      "体检目的",
      "既往史",
      "过敏史",
      "体格检查",
      "检验结果",
      "检查结论",
      "健康建议",
    ],
  },
] as const;
