export const DEPARTMENTS = [
  "全科医学科",
  "心血管内科",
  "呼吸内科",
  "消化内科",
  "内分泌科",
  "神经内科",
  "肾内科",
  "普通外科",
  "骨科",
  "神经外科",
  "胸外科",
  "妇产科",
  "儿科",
  "急诊科",
  "重症医学科",
  "肿瘤科",
  "康复医学科",
  "皮肤科",
  "眼科",
  "耳鼻咽喉科",
  "口腔科",
  "精神心理科",
  "中医科",
  "医学影像科",
  "检验科",
  "麻醉科",
];

// English labels also support searching legacy professional titles.
export const PROFESSIONAL_TITLE_LABELS: Record<string, string> = {
  "医师": "Physician",
  "住院医师": "Resident Physician",
  "主治医师": "Attending Physician",
  "副主任医师": "Associate Chief Physician",
  "主任医师": "Chief Physician",
};
