// Legacy database values are translated only for display. User-entered content is preserved.
const labels: Record<string, string> = {
  "· 健康管理": "· Health Management",
  "一次": "Once",
  "上传失败": "Upload failed",
  "上传数据": "Upload data",
  "上传监测": "Upload measurements",
  "上级医生": "Senior doctor",
  "下次评估": "Next assessment",
  "下次评估时间": "Next assessment time",
  "下次评估：": "Next assessment:",
  "两次输入的密码不一致": "Passwords do not match",
  "个性化健康目标": "Personal health goals",
  "个性化目标": "Personal goals",
  "临时专家意见": "Temporary expert opinion",
  "为本计划生成患者专属链接": "Create a patient link for this plan",
  "主任医师": "Chief Physician",
  "主治医师": "Attending Physician",
  "代录监测数据": "Record measurements",
  "会诊总结": "Conference summary",
  "会诊意见": "Conference opinion",
  "会诊详情": "Conference details",
  "会诊说明 / 总结": "Conference notes / summary",
  "会诊邀请已发送": "Conference invitations sent",
  "住院医师": "Resident Physician",
  "住院病历": "Inpatient Record",
  "体检报告": "Physical Examination Report",
  "作者 / 审核人": "Author / Reviewer",
  "例如：家用血压计": "Example: home blood pressure monitor",
  "保存失败": "Save failed",
  "保存总结并完成": "Save summary and complete",
  "保存草稿": "Save draft",
  "修改": "Edit",
  "修改医嘱": "Edit order",
  "修改密码失败": "Failed to change password",
  "停止": "Stop",
  "停止医嘱": "Stop order",
  "停止原因": "Reason for stopping",
  "健康指导": "Health guidance",
  "健康提醒": "Health reminders",
  "健康监测": "Health monitoring",
  "健康目标": "Health goals",
  "健康计划已保存": "Health plan saved",
  "健康评估": "Health assessment",
  "全部状态": "All statuses",
  "全部科室": "All departments",
  "全部等级": "All levels",
  "其它": "Other",
  "冠心病": "Coronary Heart Disease",
  "删除会诊": "Delete conference",
  "删除此会诊并取消邀请？": "Delete this conference and cancel its invitations?",
  "删除此草稿？": "Delete this draft?",
  "删除此计划及其监测、评估、提醒记录？": "Delete this plan and its measurements, assessments, and reminders?",
  "删除草稿": "Delete draft",
  "删除计划": "Delete plan",
  "到期后自动送达患者入口消息列表": "Automatically delivered to the patient portal when due",
  "到期时间：": "Expires:",
  "制定健康计划": "Create Health Plan",
  "刷新": "Refresh",
  "副主任医师": "Associate Chief Physician",
  "加载健康计划": "Loading health plan",
  "加载档案失败": "Failed to load profile",
  "加载管理数据失败": "Failed to load administration data",
  "医嘱名称": "Order name",
  "医嘱类别": "Order category",
  "医嘱（": "Orders (",
  "医师": "Physician",
  "历史会诊专家：": "Previous conference experts:",
  "参会医生": "Participating doctors",
  "参会医生 / 科室": "Doctors / Departments",
  "发起人": "Initiator",
  "发起医生": "Initiating doctor",
  "发起跨科室会诊": "Start multidisciplinary conference",
  "发送邀请": "Send invitations",
  "名称": "Name",
  "周期": "Frequency",
  "图文": "Text and Image",
  "在下方医生列表中勾选": "Select doctors from the list below",
  "在管": "Active",
  "填写本科室的会诊意见": "Enter your department's opinion",
  "备注": "Notes",
  "天": "days",
  "失败": "Failed",
  "女": "Female",
  "完成会诊": "Complete conference",
  "审核意见": "Review comments",
  "审核病历": "Review record",
  "审核结果": "Review decision",
  "审核记录": "Review history",
  "密码已修改": "Password changed",
  "尚未安排下次评估": "Next assessment has not been scheduled",
  "尚未指定": "Not assigned",
  "尚未提交审核": "Not submitted for review",
  "已保存": "Saved",
  "已停止": "Stopped",
  "已发送 / 已结束": "Sent / Finished",
  "已取消": "Cancelled",
  "已完成": "Completed",
  "已审核": "Reviewed",
  "已归档": "Archived",
  "已归档 ·": "Archived ·",
  "已拒绝": "Declined",
  "已接受": "Accepted",
  "已转出": "Transferred",
  "已退回": "Returned",
  "已选参会医生（可跨多个科室）": "Selected doctors (multiple departments supported)",
  "建议：": "Advice:",
  "开具医嘱": "Create order",
  "开始会诊": "Start conference",
  "异常": "Abnormal",
  "归档后病历及医嘱将锁定，确认归档？": "Archiving locks the record and its orders. Archive now?",
  "归档病历": "Archive record",
  "当前评估等级": "Current assessment level",
  "待会诊": "Awaiting Conference",
  "待响应": "Pending Response",
  "待安排": "Not scheduled",
  "待审核": "Pending Review",
  "待执行": "Pending",
  "待接诊": "Awaiting Consultation",
  "待随访": "Follow-up Due",
  "患者、病历编号或诊断": "Patient, record ID, or diagnosis",
  "患者健康管理": "Patient Health Management",
  "患者入口": "Patient portal",
  "患者可通过链接上传血压、血糖并查看健康提醒。链接有效期为 7 天；重新生成会使旧链接失效。": "Patients can upload blood pressure and glucose readings and view reminders. Links expire in 7 days. Generating a new link invalidates the previous link.",
  "患者已收到的消息": "Messages delivered to the patient",
  "慢阻肺": "Chronic Obstructive Pulmonary Disease",
  "成功": "Success",
  "我发起或受邀的会诊 · 每 10 秒刷新": "Conferences I initiated or was invited to · Refreshes every 10 seconds",
  "我的健康管理": "My Health Management",
  "我的身份": "My role",
  "手工录入": "Manual entry",
  "打开患者入口": "Open patient portal",
  "执行中": "Active",
  "执行说明": "Instructions",
  "执行说明（剂量、频次、途径或检查要求）": "Instructions (dose, frequency, route, or examination requirements)",
  "拒绝邀请": "Decline invitation",
  "按患者 / 会诊主题搜索": "Search by patient or conference topic",
  "授权失败": "Failed to grant permission",
  "授权说明": "Reason for access",
  "接受邀请": "Accept invitation",
  "提交上级审核": "Submit for senior review",
  "提交会诊意见": "Submit opinion",
  "提交审核": "Submit for review",
  "提醒与消息": "Reminders and messages",
  "提醒内容": "Reminder message",
  "搜索医生姓名 / 职称": "Search by doctor name or title",
  "搜索患者或计划": "Search by patient or plan",
  "搜索病历": "Search records",
  "撤销链接": "Revoke link",
  "操作失败": "Operation failed",
  "操作成功": "Operation completed",
  "收缩压（mmHg）": "Systolic pressure (mmHg)",
  "数值": "Value",
  "新增健康评估": "Add health assessment",
  "新建病历": "Create Medical Record",
  "无": "None",
  "暂无": "Not available",
  "暂无上传": "No uploads yet",
  "暂无会诊意见": "No opinions yet",
  "暂无可选上级医生，请在管理授权中为另一位医生赋予 senior_doctor 角色。": "No senior doctors available. Assign the Senior Doctor role to another doctor in Access Management.",
  "暂无提醒消息": "No reminders yet",
  "暂无消息": "No messages yet",
  "暂无监测": "No measurements yet",
  "暂无监测记录": "No measurements yet",
  "暂无评估记录": "No assessments yet",
  "更新": "Updated",
  "更新角色失败": "Failed to update roles",
  "最新监测": "Latest measurement",
  "未关联患者": "No patient linked",
  "未分配角色": "No role assigned",
  "未填写": "Not provided",
  "未设置": "Not set",
  "未设置科室": "Department not set",
  "来源": "Source",
  "查看 / 处理": "View / Manage",
  "查看 / 管理": "View / Manage",
  "查看会诊": "View conference",
  "档案已更新": "Profile updated",
  "检查": "Examination",
  "检验": "Laboratory Test",
  "正常": "Normal",
  "每": "Every",
  "每 10 秒刷新 ·": "Refreshes every 10 seconds ·",
  "汇总各科室意见，填写最终会诊总结": "Summarize the departments' opinions and enter the final conference summary",
  "测量时段": "Measurement context",
  "测量时间": "Measured at",
  "生成 / 更新患者链接": "Generate / Renew patient link",
  "生活与健康指导": "Lifestyle and health guidance",
  "生活方式、监测与随访建议": "Lifestyle, monitoring, and follow-up advice",
  "男": "Male",
  "病历已保存": "Medical record saved",
  "病历已归档": "Medical record archived",
  "病历状态": "Record status",
  "病历详情": "Medical Record Details",
  "病情摘要 / 会诊目的": "Case summary / Conference purpose",
  "监测历史": "Measurement history",
  "监测数据已上传，医生可以查看": "Measurements uploaded and available to your doctor",
  "监测项目": "Measurement type",
  "确认": "Confirm",
  "确认拒绝本次邀请？": "Decline this invitation?",
  "空腹": "Fasting",
  "等待至少一名医生接受邀请后开始会诊": "Wait for at least one doctor to accept before starting",
  "等级：": "Level:",
  "筛选科室": "Filter department",
  "管理员查看": "Administrator view",
  "管理计划": "Management plan",
  "类别": "Category",
  "糖尿病": "Diabetes",
  "结构化模板": "Structured template",
  "编号": "ID",
  "编辑病历": "Edit Medical Record",
  "联合会诊意见": "Multidisciplinary opinions",
  "至少选择一名医生": "Select at least one doctor",
  "舒张压（mmHg）": "Diastolic pressure (mmHg)",
  "草稿": "Draft",
  "药物": "Medication",
  "血压": "Blood pressure",
  "血压（mmHg）": "Blood pressure (mmHg)",
  "血糖": "Blood glucose",
  "血糖（mmol/L）": "Blood glucose (mmol/L)",
  "补充病历": "Additional notes",
  "补充病历内容": "Additional record content",
  "视频": "Video",
  "计划名称": "Plan name",
  "计划时间": "Scheduled time",
  "计划调整：": "Plan change:",
  "设备 / 数据来源": "Device / Data source",
  "设置健康提醒": "Set health reminder",
  "设置提醒任务": "Schedule reminder",
  "评估等级": "Assessment level",
  "评估结论": "Assessment conclusion",
  "评估记录": "Assessment history",
  "评估：": "Assessment:",
  "请填写会诊总结": "Enter a conference summary",
  "请求失败": "Request failed",
  "请联系负责医生获取新的患者链接。": "Contact your doctor for a new patient link.",
  "课程演示会诊支持": "Course demo consultation support",
  "调整健康计划": "Adjust Health Plan",
  "调整后的健康建议（同步给患者）": "Updated health advice (shared with the patient)",
  "调整计划名称（选填）": "Revised plan name (optional)",
  "跨科室联合会诊": "Multidisciplinary Conferences",
  "进行中": "In Progress",
  "退回修改": "Return for changes",
  "选择性别": "Select gender",
  "选择所属科室": "Select department",
  "选择职称": "Select professional title",
  "通过最终审核": "Approve final review",
  "邀请状态": "Invitation status",
  "重复间隔（天，0 为一次）": "Repeat interval (days, 0 for once)",
  "链接已撤销": "Link revoked",
  "门诊病历": "Outpatient Record",
  "随机": "Random",
  "项目": "Type",
  "预约时间": "Scheduled time",
  "预警": "Warning",
  "餐后": "After meal",
  "首次提醒时间": "First reminder time",
  "高血压": "Hypertension",
  "（历史记录）": "(Historical record)",
  "上传头像（multipart/form-data 字段名 file）": "Upload avatar (multipart/form-data field: file)",
  "上传成功": "Upload successful",
  "下次评估时间必须晚于当前时间": "The next assessment must be scheduled in the future",
  "不能审核自己的病历": "You cannot review your own record",
  "不能移除自己的管理员角色": "You cannot remove your own administrator role",
  "专科检查": "Specialist examination",
  "中医科": "Traditional Chinese Medicine",
  "临时权限不存在或已撤销": "Temporary permission not found or already revoked",
  "临时权限已撤销": "Temporary permission revoked",
  "主要症状": "Main symptoms",
  "主诉": "Chief complaint",
  "仅会诊开始前可调整参会名单": "Participants can only be changed before the conference starts",
  "仅作者或管理员可修改病历": "Only the author or an administrator can edit this record",
  "仅医生可发起会诊": "Only doctors can initiate a conference",
  "仅发起人或管理员可删除会诊": "Only the initiator or an administrator can delete this conference",
  "仅发起人或管理员可管理会诊": "Only the initiator or an administrator can manage this conference",
  "仅指定的上级医生可以审核": "Only the assigned senior doctor can review this record",
  "仅支持 JPG / PNG / WebP / GIF 图片": "Only JPG, PNG, WebP, and GIF images are supported",
  "仅草稿或退回病历可以修改；审核及归档病历已锁定": "Only draft or returned records can be edited. Records under review or archived are locked.",
  "仅进行中的会诊可提交意见": "Opinions can only be submitted during an active conference",
  "仅通过最终审核的病历可以归档": "Only records that passed final review can be archived",
  "会诊不存在": "Conference not found",
  "会诊列表（分页 + 搜索）": "List conferences (pagination and search)",
  "会诊字段不能为空或 null": "Conference fields cannot be empty or null",
  "会诊字段无效": "Invalid conference fields",
  "会诊已开始或结束，不能再响应邀请": "Invitations cannot be answered after the conference has started or ended",
  "住院病历模板": "Inpatient record template",
  "体格检查": "Physical examination",
  "体检报告模板": "Physical examination report template",
  "体检目的": "Purpose of examination",
  "你不是受邀医生": "You are not an invited doctor",
  "修改密码": "Change password",
  "修改患者档案": "Update patient profile",
  "修改用户角色": "Update user roles",
  "修改病历": "Edit medical record",
  "健康建议": "Health advice",
  "健康提醒发送失败，将在下一轮重试": "Health reminder delivery failed; retrying on the next cycle",
  "健康管理": "Health Management",
  "健康计划": "Health plan",
  "健康计划不存在": "Health plan not found",
  "健康计划不能为空": "Health plan cannot be empty",
  "健康评估建议：": "Health assessment advice:",
  "儿科": "Pediatrics",
  "入院查体": "Admission examination",
  "入院诊断依据": "Admission diagnosis rationale",
  "全科医学科": "General Practice",
  "关键词（操作人/对象/类型）": "Keyword (actor, target, or action)",
  "内分泌科": "Endocrinology",
  "内容（须已脱敏）": "Content (must be de-identified)",
  "删除健康计划": "Delete health plan",
  "删除帖子": "Delete post",
  "删除患者": "Delete patient",
  "删除成功": "Deleted successfully",
  "删除草稿病历": "Delete draft record",
  "删除问诊": "Delete consultation",
  "刷新Token": "Refresh token",
  "医嘱": "Orders",
  "医嘱不存在": "Order not found",
  "医嘱名称和执行说明不能为空": "Order name and instructions cannot be empty",
  "医嘱已经停止": "Order has already been stopped",
  "医学影像科": "Medical Imaging",
  "医生服务系统 API": "Doctor Services API",
  "医生社交": "Doctor Community",
  "单场会诊最多保留300条意见": "A conference can contain at most 300 opinions",
  "发布病例分享": "Publish case discussion",
  "发起人无需重复邀请自己": "The initiator does not need to invite themselves",
  "发起会诊": "Start conference",
  "取消健康提醒": "Cancel health reminder",
  "口腔科": "Dentistry",
  "呼吸内科": "Respiratory Medicine",
  "响应会诊邀请": "Respond to conference invitation",
  "在线问诊": "Consultations",
  "妇产科": "Obstetrics and Gynecology",
  "姓名": "Name",
  "字段不能为 null": "Fields cannot be null",
  "字段不能为 null，请使用空字符串清空文本": "Fields cannot be null. Use an empty string to clear text.",
  "审计日志列表（仅管理员）": "List audit logs (administrators only)",
  "密码修改成功": "Password changed successfully",
  "密码至少 6 位": "Password must be at least 6 characters",
  "已不在会诊名单中": "You are no longer a conference participant",
  "已停止医嘱不可修改": "Stopped orders cannot be edited",
  "已响应过此邀请": "You have already responded to this invitation",
  "已完成会诊不可修改": "Completed conferences cannot be edited",
  "已开始或完成的会诊不能删除": "Started or completed conferences cannot be deleted",
  "已撤销": "Revoked",
  "已有医嘱或审核记录的病历不可删除": "Records with orders or review history cannot be deleted",
  "帖子不存在": "Post not found",
  "帖子列表（分页 + 搜索）": "List posts (pagination and search)",
  "帖子详情": "Post details",
  "年龄": "Age",
  "康复医学科": "Rehabilitation Medicine",
  "开具": "Created",
  "归档": "Archived",
  "当前密码不正确": "Current password is incorrect",
  "当前账号没有医生角色": "The current account does not have a doctor role",
  "录入健康监测": "Record health measurement",
  "心血管内科": "Cardiology",
  "急诊科": "Emergency Medicine",
  "性别": "Gender",
  "患者ID": "Patient ID",
  "患者上传": "Patient upload",
  "患者不存在": "Patient not found",
  "患者列表（分页 + 搜索）": "List patients (pagination and search)",
  "患者管理": "Patients",
  "患者详情": "Patient details",
  "患者链接无效或已过期": "Patient link is invalid or expired",
  "意见不能为空": "Opinion cannot be empty",
  "授予临时权限": "Grant temporary permission",
  "提交病历审核": "Submit record for review",
  "提交给": "Submitted to",
  "提醒不存在": "Reminder not found",
  "提醒内容不能为空": "Reminder message cannot be empty",
  "提醒时间不能早于当前时间": "Reminder time cannot be in the past",
  "搜索关键词（姓名/编号/症状/分组）": "Search keyword (name, ID, symptoms, or group)",
  "搜索关键词（患者/主题）": "Search keyword (patient or topic)",
  "搜索关键词（患者/编号）": "Search keyword (patient or ID)",
  "搜索关键词（标题/内容）": "Search keyword (title or content)",
  "撤销临时权限": "Revoke temporary permission",
  "撤销患者健康入口": "Revoke patient portal access",
  "操作人": "Actor",
  "操作审计": "Audit Log",
  "操作类型": "Action type",
  "新增患者": "Add patient",
  "新密码至少 6 位": "New password must be at least 6 characters",
  "新建问诊": "Create consultation",
  "无权为该患者创建病历": "You cannot create records for this patient",
  "无权为该患者制定计划": "You cannot create plans for this patient",
  "无权为该患者发起会诊": "You cannot initiate conferences for this patient",
  "无权访问该会诊": "You do not have access to this conference",
  "无权访问该健康计划": "You do not have access to this health plan",
  "无权访问该患者档案": "You do not have access to this patient profile",
  "无权访问该病历": "You do not have access to this record",
  "无权访问该问诊": "You do not have access to this consultation",
  "既往史": "Medical history",
  "普通外科": "General Surgery",
  "智慧医养大数据公共服务平台 - 医生服务系统 API 文档": "Smart Healthcare and Elderly Care Platform - Doctor Services API documentation",
  "更新会诊": "Update conference",
  "更新会诊（进入会诊/完成等状态流转）": "Update conference (start, complete, or change status)",
  "更新帖子": "Update post",
  "更新当前用户档案": "Update current user profile",
  "更新患者": "Update patient",
  "更新问诊": "Update consultation",
  "更新问诊（接诊/完成等状态流转）": "Update consultation (accept, complete, or change status)",
  "最新指标": "Latest metrics",
  "最终审核完成，病历锁定": "Final review completed; record locked",
  "未登录或登录已过期": "Not signed in or session expired",
  "本地提醒规则": "Local reminder rule",
  "本地模拟设备来源": "Local demo device source",
  "本地模拟附件说明": "Local demo attachment notes",
  "标题": "Title",
  "检查结论": "Examination findings",
  "检验科": "Laboratory Medicine",
  "检验结果": "Laboratory results",
  "模板与病历类型不匹配": "Template does not match the record type",
  "每页条数": "Items per page",
  "注册成功": "Registration successful",
  "测量时间不能晚于当前时间": "Measurement time cannot be in the future",
  "消化内科": "Gastroenterology",
  "演示环境不会发送短信或邮件；选择任一方式后使用演示码。": "The demo does not send text messages or emails. Choose a method and enter the demo code.",
  "演示验证码或人脸口令不正确": "Incorrect demo verification code or face passphrase",
  "点赞": "Like",
  "状态": "Status",
  "现病史": "History of present illness",
  "生成患者健康入口": "Generate patient portal access",
  "用户": "Users",
  "用户不存在": "User not found",
  "用户名不能为空": "Username cannot be empty",
  "用户名只能包含字母、数字、下划线": "Username may contain only letters, numbers, and underscores",
  "用户名已存在": "Username already exists",
  "用户名或密码错误": "Incorrect username or password",
  "用户名至少 3 个字符": "Username must be at least 3 characters",
  "用户注册": "User registration",
  "用户登录": "User sign-in",
  "电子病历": "Medical Records",
  "电话": "Phone",
  "病历不处于待审核状态": "Record is not pending review",
  "病历不存在": "Medical record not found",
  "病种分组": "Condition group",
  "登录成功，返回JWT Token": "Sign-in successful; returns a JWT token",
  "皮肤科": "Dermatology",
  "眼科": "Ophthalmology",
  "神经内科": "Neurology",
  "神经外科": "Neurosurgery",
  "科室/圈子": "Department / Community",
  "精神心理科": "Psychiatry and Psychology",
  "系统": "System",
  "结构化字段无效或超过5000字": "Structured fields are invalid or exceed 5,000 characters",
  "耳鼻咽喉科": "Otolaryngology",
  "肾内科": "Nephrology",
  "肿瘤科": "Oncology",
  "胸外科": "Thoracic Surgery",
  "自动撤销临时权限": "Automatically revoke temporary permission",
  "至少一名医生接受邀请后才能开始": "At least one doctor must accept before the conference can start",
  "至少保留一位受邀医生": "Keep at least one invited doctor",
  "获取当前用户档案": "Get current user profile",
  "血压需填写收缩压和舒张压，且收缩压应大于舒张压": "Enter systolic and diastolic pressure; systolic pressure must be higher than diastolic pressure",
  "血糖需填写数值": "Enter a blood glucose value",
  "认证": "Authentication",
  "评估健康并调整建议": "Assess health and update advice",
  "评估和建议不能为空": "Assessment and advice cannot be empty",
  "诊疗计划": "Care plan",
  "该邮箱已被占用": "This email address is already in use",
  "请上传图片文件": "Upload an image file",
  "请先接受会诊邀请": "Accept the conference invitation first",
  "请先选择结构化模板": "Select a structured template first",
  "请填写停止原因": "Enter a reason for stopping",
  "请填写审核意见": "Enter review comments",
  "请填写病历内容": "Enter record content",
  "请填写诊断": "Enter a diagnosis",
  "请按开始会诊、完成会诊的顺序操作": "Start the conference before completing it",
  "请至少选择一名参会医生": "Select at least one participating doctor",
  "请输入当前密码": "Enter your current password",
  "请选择医生账号，不要同时提交手填专家姓名": "Select doctor accounts without also entering expert names manually",
  "请选择有效且在职的医生账号": "Select valid, active doctor accounts",
  "请选择有效的上级医生": "Select a valid senior doctor",
  "账号已停用": "Account disabled",
  "账户当前不可登录": "This account cannot sign in",
  "辅助检查": "Additional examinations",
  "过敏史": "Allergies",
  "过期时间必须晚于当前时间": "Expiry time must be in the future",
  "远程会诊": "Remote Conferences",
  "邀请的医生账号ID": "Invited doctor account IDs",
  "邮箱已被注册": "Email address already registered",
  "邮箱格式不正确": "Enter a valid email address",
  "重症医学科": "Intensive Care",
  "门诊病历模板": "Outpatient record template",
  "问诊列表（分页 + 搜索）": "List consultations (pagination and search)",
  "问诊类型": "Consultation type",
  "问诊记录不存在": "Consultation not found",
  "问诊详情": "Consultation details",
  "页码": "Page number",
  "预警等级": "Alert level",
  "骨科": "Orthopedics",
  "麻醉科": "Anesthesiology",
  "📚 API 文档: http://localhost:": "API documentation: http://localhost:",
  "🚀 医生服务系统后端运行在: http://localhost:": "Doctor Services backend running at: http://localhost:",
  "（医生代录）": " (entered by doctor)",
  "admin": "Administrator",
  "doctor": "Doctor",
  "senior_doctor": "Senior Doctor",
  "consultation_expert": "Consultation Expert"
};

export const displayLabel = (value: string | null | undefined): string => value ? labels[value] || value : "-";

// Translate only known system-generated text from older records.
export function displaySystemText(value?: string | null): string {
  if (!value) return "-";
  if (labels[value]) return labels[value];
  return value.replace(/^血压(?=\s)/, "Blood pressure").replace(/^血糖(?=\s)/, "Blood glucose").replace(/^健康评估建议：/, "Health assessment advice: ").replace(/^提交给\s*/, "Submitted to ").replace(/（医生代录）$/, " (entered by doctor)");
}
